package com.projectmimir.finr

object AppText {
    const val APP_NAME = "ꜰɪɴʀ"
    const val APP_NAME_PLAIN = "finr"
    const val LOGO_DESC = "finr logo"
    const val MENU_DESC = "Menu"
    const val TOGGLE_SMS_DESC = "Toggle SMS"
    const val ADD_TXN_DESC = "Add Transaction"
    const val CALENDAR_DESC = "Calendar"
    const val EXPORT_DESC = "Export"
    const val EXPORT_DATA = "Export Data"
    const val EXPORT_YEAR = "Year"
    const val EXPORT_MONTH = "Month"
    const val EXPORT_ALL_MONTHS = "All"
    const val EXPORT_SAVE = "Save CSV"
    const val EXPORT_SHARE = "Share CSV"
    const val EXPORT_SELECT_YEAR = "Select a year"
    const val EXPORT_SELECT_MONTH = "Select a month or All"
    const val EXPORT_NO_DATA = "No transactions available for selected period"
    const val EXPORT_SAVE_SUCCESS = "CSV saved"
    const val EXPORT_SAVE_FAIL = "Failed to save CSV"
    const val EXPORT_SHARE_FAIL = "Failed to share CSV"

    const val PERMISSION_TITLE = "SMS permission needed"
    const val PERMISSION_DESC = "This app reads SMS messages to show them as a transaction list. Your data cannot be viewed/accessed by us."
    const val PERMISSION_BUTTON = "Grant permission"
    const val LOADING = "Loading .."
    const val SPLASH_TAGLINE = "finr"
    const val SPLASH_POWERED_BY = "Powered by Project Mimir"
    const val NO_TRANSACTIONS = "No transactions found."
    const val REFRESH_NEW = "New transactions fetched"
    const val REFRESH_NONE = "No new transactions found"
    const val DAILY_NOTIF_CHANNEL_NAME = "Daily Summary"
    const val DAILY_NOTIF_CHANNEL_DESC = "Daily transaction summary notifications"
    const val DAILY_NOTIF_TITLE = "Daily Summary"
    const val DAILY_NOTIF_SENT_PREFIX = "Sent "
    const val DAILY_NOTIF_RECEIVED_PREFIX = "Received "

    const val CALENDAR_DIALOG_TITLE = "Filter Transactions"
    const val CALENDAR_FIELD = "Date / Month"
    const val WHOLE_MONTH = "Whole month"
    const val APPLY = "Apply"
    const val CANCEL = "Cancel"
    const val SELECT_DATE_FIRST = "Select a date first"

    const val ABOUT_BUILD = "Pre Alpha build"
    const val VERSION = "Version"
    const val OK = "OK"
    const val CLOSE = "Close"

    const val EDIT = "Edit"
    const val SMS = "SMS"
    const val USER_CREATED = "User created"
    const val UNKNOWN_SENDER = "Unknown Sender"

    const val DAILY_SUMMARY = "DAILY SUMMARY"
    const val MONTHLY_SUMMARY = "MONTHLY SUMMARY"
    const val SENT = "Sent"
    const val RECEIVED = "Received"

    const val SETTINGS = "Settings"
    const val ABOUT = "About"
    const val DB = "DB"
    const val RECYCLE = "Recycle"
    const val SECURE = "Secure"
    const val THEME = "Theme"
    const val THEME_TITLE = "Select Theme"
    const val THEME_LIGHT = "Light"
    const val THEME_DARK = "Dark"
    const val THEME_MIDNIGHT = "Midnight"

    const val SECURE_MODE = "Secure mode enabled"
    const val AUTH_PROMPT = "Authenticate to continue."
    const val UNLOCK = "Unlock"
    const val ENABLE = "Enable"
    const val DISABLE = "Disable"
    const val ENABLE_SECURE_TITLE = "Enable Secure Mode?"
    const val ENABLE_SECURE_DESC = "Biometric or device PIN will be required on app open."
    const val DISABLE_SECURE_TITLE = "Disable Secure Mode?"
    const val DISABLE_SECURE_DESC = "Biometric check will be removed on next app open."

    const val RECYCLE_TITLE = "Recycle transactions?"
    const val RECYCLE_DESC = "This will delete all saved transactions and rebuild from device SMS."

    const val DB_NO_SCHEMA = "No DB schema found."
    const val DB_TABLE = "Table"
    const val DB_NO_COLUMNS = "No columns"
    const val DB_UNKNOWN = "UNKNOWN"

    const val BACK = "Back"

    const val DISCARD = "Discard"
    const val KEEP_EDITING = "Keep Editing"
    const val DELETE = "Delete"
    const val SAVE = "Save"
    const val UPDATE = "Update"

    const val DISCARD_CHANGES_TITLE = "Discard changes?"
    const val DISCARD_NEW_TITLE = "Discard new transaction?"
    const val UNSAVED_CHANGES = "You have unsaved changes."
    const val DELETE_TXN_TITLE = "Delete transaction?"
    const val DELETE_TXN_DESC = "This cannot be undone."
    const val DELETE_TXN_BUTTON = "Delete Transaction"
    const val UPDATE_CATEGORY = "Update Category"
    const val CATEGORY_NOT_FOUND = "Category/Sub Category not found"

    const val EDIT_TXN = "Edit Transaction"
    const val ADD_TXN = "Add Transaction"
    const val IMPORT_SMS = "Import SMS"
    const val IMPORT_SMS_PASTE = "Paste SMS"
    const val IMPORT_SMS_EMPTY = "Paste an SMS first"
    const val IMPORT_SMS_FAIL = "Failed to process SMS"
    const val IMPORT_SMS_SUCCESS = "SMS imported successfully"
    const val SHARED_TEXT_IMPORT_FAIL = "Unable to extract transaction details from shared text."
    const val SHARED_TEXT_IMPORT_EXIT = "Exit"
    const val IMPORTED_SMS_SOURCE = "Imported SMS"
    const val USER = "User"

    const val AMOUNT = "Amount"
    const val AMOUNT_RUPEE = "Amount (₹)"
    const val DATE = "Date"
    const val TIME = "Time"
    const val SENDER = "Sender"
    const val TXN_TYPE = "Transaction Type"
    const val CATEGORY = "Category"
    const val SUBCATEGORY = "Sub Category"

    const val MISC = "Miscellaneous"
    const val UNCAT = "Uncategorised"
    const val UNCLASSIFIED = "Unclassified"
    const val CREDIT = "credit"
    const val DEBIT = "debit"
    const val CREDIT_UPPER = "CREDIT"
    const val DEBIT_UPPER = "DEBIT"
    const val USER_T = "USER-T"

    const val FUTURE_DATE_TIME_NOT_ALLOWED = "Future date/time not allowed"
    const val FUTURE_TIME_NOT_ALLOWED = "Future time not allowed"

    const val DB_TITLE = "DB"
    const val DB_TABLE_PREFIX = "Table: "
    const val DOUBLE_SPACE = "  "
    const val DATE_FMT_DAY = "dd MMM yyyy"
    const val DATE_FMT_MONTH = "MMM yyyy"
    const val KEY_DAILY_PREFIX = "daily-"
    const val KEY_MONTHLY_PREFIX = "monthly-"
    const val KEY_DAY_PREFIX = "day-"
    const val COLON_SPACE = ": "

    const val BIO_TITLE = "Secure Access"
    const val BIO_SUBTITLE = "Authenticate to enable secure mode"

    const val TXNC_UPI = "UPI"
    const val TXNC_CARD = "CARD"
    const val CSV_FILE_PREFIX = "finr_transactions_"

    const val PREFS_NAME = "finr_prefs"
    const val PREF_SECURE_ENABLED = "secure_enabled"
    const val PREF_CATEGORIES_SEEDED = "seeded_categories_v3"
    const val PREF_BANK_BACKFILL_DONE = "bank_backfill_done_v1"
    const val PREF_THEME_MODE = "theme_mode"
    const val PREF_THEME_DARK = "theme_dark"
    const val DB_NAME = "sms_reader.db"
}
